export const catalogFixture = {
    schemaVersion: 1,
    items: [{
        id: 1,
        name_kr: "테스트 모자",
        name_en: "Test Hat",
        useType: "",
        maxUse: 0,
        hidden: false,
        resist: "",
        character: "Niki",
        part: "Hat",
        level: 1,
        str: 2,
        sta: 0,
        dex: 0,
        wil: 0,
        hp: 0,
        quickslots: 1,
        buffslots: 0,
        smash: 0,
        movement: 3,
        charge: 0,
        lob: 0,
        serve: 0,
        max_str: 0,
        max_sta: 0,
        max_dex: 0,
        max_wil: 0,
        element_enchantable: false,
        parcel_enabled: true,
        spin: 0,
        atss: 0,
        dfss: 0,
        socket: 0,
        gauge: 0,
        gauge_battle: 0,
    }],
    products: [
        {
            productIndex: 100,
            kind: "parts",
            name: "Test Hat",
            enabled: true,
            purchasable: true,
            price: 900,
            ap: false,
            itemIds: [1],
            gachaIndex: null,
        },
        {
            productIndex: 200,
            kind: "lottery",
            name: "Test Coin",
            enabled: true,
            purchasable: true,
            price: 50,
            ap: true,
            itemIds: [1],
            gachaIndex: 7,
        },
    ],
    gachas: [{
        productIndex: 200,
        drops: [{
            character: "Niki",
            shopProductIndex: 100,
            probability: 25,
            quantityMin: 1,
            quantityMax: 1,
        }],
    }],
    stageSources: [{
        attachedProductIndex: 100,
        rewardProductIndexes: [100],
        map: "Test Arena",
        xp: 10,
        needBoss: true,
        bossTime: 90,
    }],
    art: {
        item: { items: {}, lotteries: {}, sheets: {} },
        map: { files: {}, byName: {} },
        stageBoss: { bosses: {}, guardians: {}, stages: {} },
        boss: {},
    },
};
